<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mobiles</name>
   <tag></tag>
   <elementGuidId>e1636d9e-fe1e-46c7-a8fa-2202e71e2d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.lzd-site-menu-grand-item > a > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Mobiles']/parent::*</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;J_8636740892&quot;)/div[@class=&quot;lzd-site-nav-menu-dropdown&quot;]/ul[@class=&quot;lzd-site-menu-root&quot;]/ul[@class=&quot;lzd-site-menu-sub Level_1_Category_No1 lzd-site-menu-sub-active&quot;]/li[@class=&quot;lzd-site-menu-sub-item&quot;]/ul[@class=&quot;lzd-site-menu-grand lzd-site-menu-grand-active&quot;]/li[@class=&quot;lzd-site-menu-grand-item&quot;]/a[1]/span[1][count(. | //*[(text() = 'Mobiles' or . = 'Mobiles')]) = count(//*[(text() = 'Mobiles' or . = 'Mobiles')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spm-anchor-id</name>
      <type>Main</type>
      <value>a2o4k.home.cate_1_1.i0.75f82e7evdJqei</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobiles</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;J_8636740892&quot;)/div[@class=&quot;lzd-site-nav-menu-dropdown&quot;]/ul[@class=&quot;lzd-site-menu-root&quot;]/ul[@class=&quot;lzd-site-menu-sub Level_1_Category_No1 lzd-site-menu-sub-active&quot;]/li[@class=&quot;lzd-site-menu-sub-item&quot;]/ul[@class=&quot;lzd-site-menu-grand lzd-site-menu-grand-active&quot;]/li[@class=&quot;lzd-site-menu-grand-item&quot;]/a[1]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='J_8636740892']/div/ul/ul/li/ul/li/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobiles &amp; Tablets'])[1]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automotive &amp; Motorcycles'])[1]/following::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tablets'])[1]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Landline Phones'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mobiles']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a/span</value>
   </webElementXpaths>
</WebElementEntity>
